class OrderItem {
  final String? id;
  final String? orderId;
  final String inventoryItemId;

  // Join-derived — not stored in order_items, populated via inventory_items join.
  final String itemTitle;
  final String itemSku;

  final double priceAtSale;
  final int quantity;

  const OrderItem({
    this.id,
    this.orderId,
    required this.inventoryItemId,
    this.itemTitle = '',
    this.itemSku = '',
    required this.priceAtSale,
    required this.quantity,
  });

  double get subtotal => priceAtSale * quantity;

  factory OrderItem.fromMap(Map<String, dynamic> map) {
    final inv = map['inventory_items'] as Map<String, dynamic>?;
    return OrderItem(
      id: map['id']?.toString(),
      orderId: map['order_id']?.toString(),
      inventoryItemId: map['inventory_item_id']?.toString() ?? '',
      itemTitle: inv?['title']?.toString() ?? '',
      itemSku: inv?['sku']?.toString() ?? '',
      priceAtSale: (map['price_at_sale'] ?? 0).toDouble(),
      quantity: (map['quantity'] ?? 1) as int,
    );
  }

  Map<String, dynamic> toMap() => {
        if (orderId != null) 'order_id': orderId,
        'inventory_item_id': inventoryItemId,
        'price_at_sale': priceAtSale,
        'quantity': quantity,
      };
}

// ─────────────────────────────────────────────────────────────────────────────

class Order {
  final String? id;
  final String? customerId;

  // Join-derived from customers table.
  final String customerName;

  // Auto-generated by DB sequence — not sent on insert.
  final String orderNumber;

  /// 'draft' | 'confirmed' | 'paid' | 'cancelled'
  final String status;

  final DateTime orderDate;
  final String notes;

  // Populated when loaded via getOrderDetail / getOrdersForCustomer.
  final List<OrderItem> items;

  final String? branchId;
  final DateTime? createdAt;

  const Order({
    this.id,
    this.customerId,
    this.customerName = '',
    this.orderNumber = '',
    required this.status,
    required this.orderDate,
    required this.notes,
    this.items = const [],
    this.branchId,
    this.createdAt,
  });

  double get total =>
      items.fold(0.0, (sum, i) => sum + i.priceAtSale * i.quantity);

  factory Order.fromMap(Map<String, dynamic> map) {
    List<OrderItem> parseItems(dynamic value) {
      if (value is! List) return const [];
      return value
          .map<OrderItem>((e) => OrderItem.fromMap(e as Map<String, dynamic>))
          .toList();
    }

    final customer = map['customers'] as Map<String, dynamic>?;
    return Order(
      id: map['id']?.toString(),
      customerId: map['customer_id']?.toString(),
      customerName: customer?['name']?.toString() ?? '',
      orderNumber: map['order_number']?.toString() ?? '',
      status: map['status'] ?? 'draft',
      orderDate: map['order_date'] != null
          ? DateTime.parse(map['order_date'].toString())
          : DateTime.now(),
      notes: map['notes'] ?? '',
      items: parseItems(map['order_items']),
      branchId: map['branch_id']?.toString(),
      createdAt: map['created_at'] != null
          ? DateTime.parse(map['created_at'])
          : null,
    );
  }

  /// Does NOT include order_number (auto-generated by DB) or items.
  Map<String, dynamic> toMap() => {
        'customer_id': customerId,
        'status': status,
        'order_date':
            '${orderDate.year.toString().padLeft(4, '0')}-'
            '${orderDate.month.toString().padLeft(2, '0')}-'
            '${orderDate.day.toString().padLeft(2, '0')}',
        'notes': notes,
        'branch_id': branchId,
      };

  Order copyWith({
    String? id,
    Object? customerId = _omitted,
    String? customerName,
    String? orderNumber,
    String? status,
    DateTime? orderDate,
    String? notes,
    List<OrderItem>? items,
    Object? branchId = _omitted,
    DateTime? createdAt,
  }) {
    return Order(
      id: id ?? this.id,
      customerId: identical(customerId, _omitted)
          ? this.customerId
          : customerId as String?,
      customerName: customerName ?? this.customerName,
      orderNumber: orderNumber ?? this.orderNumber,
      status: status ?? this.status,
      orderDate: orderDate ?? this.orderDate,
      notes: notes ?? this.notes,
      items: items ?? this.items,
      branchId:
          identical(branchId, _omitted) ? this.branchId : branchId as String?,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}

const _omitted = Object();
