class OrderItem {
  final String? id;
  final String? orderId;
  final String inventoryItemId;

  // Join-derived — not stored in order_items, populated via inventory_items join.
  final String itemTitle;
  final String itemSku;

  final double priceAtSale;
  final int quantity;

  const OrderItem({
    this.id,
    this.orderId,
    required this.inventoryItemId,
    this.itemTitle = '',
    this.itemSku = '',
    required this.priceAtSale,
    required this.quantity,
  });

  double get subtotal => priceAtSale * quantity;

  factory OrderItem.fromMap(Map<String, dynamic> map) {
    final inv = map['inventory_items'] as Map<String, dynamic>?;
    return OrderItem(
      id: map['id']?.toString(),
      orderId: map['order_id']?.toString(),
      inventoryItemId: map['inventory_item_id']?.toString() ?? '',
      itemTitle: inv?['title']?.toString() ?? '',
      itemSku: inv?['sku']?.toString() ?? '',
      priceAtSale: (map['price_at_sale'] ?? 0).toDouble(),
      quantity: (map['quantity'] ?? 1) as int,
    );
  }

  Map<String, dynamic> toMap() => {
        if (orderId != null) 'order_id': orderId,
        'inventory_item_id': inventoryItemId,
        'price_at_sale': priceAtSale,
        'quantity': quantity,
      };
}

// ─────────────────────────────────────────────────────────────────────────────

class Order {
  final String? id;
  final String? customerId;

  // Join-derived from customers table.
  final String customerName;

  // Auto-generated by DB sequence — not sent on insert.
  final String orderNumber;

  /// 'draft' | 'confirmed' | 'paid' | 'cancelled'
  final String status;

  final DateTime orderDate;
  final String notes;

  // Populated when loaded via getOrderDetail / getOrdersForCustomer.
  final List<OrderItem> items;

  final String? sellerId;
  final DateTime? createdAt;

  // ── Sell-engine fields ────────────────────────────────────────────────────

  /// 'manual' | 'platform'
  final String saleChannel;

  /// Seller's commission rate at the time of sale (e.g. 0.10 = 10 %).
  final double commissionRate;

  /// commissionRate × orderTotal, rounded to 2 d.p.
  final double commissionAmount;

  /// orderTotal − commissionAmount.
  final double sellerPayout;

  /// Denormalised sum of line-item prices; stored at sale time.
  final double orderTotal;

  const Order({
    this.id,
    this.customerId,
    this.customerName = '',
    this.orderNumber = '',
    required this.status,
    required this.orderDate,
    required this.notes,
    this.items = const [],
    this.sellerId,
    this.createdAt,
    this.saleChannel = 'manual',
    this.commissionRate = 0,
    this.commissionAmount = 0,
    this.sellerPayout = 0,
    this.orderTotal = 0,
  });

  /// Computed from loaded items — use orderTotal for the stored, authoritative value.
  double get total =>
      items.fold(0.0, (sum, i) => sum + i.priceAtSale * i.quantity);

  factory Order.fromMap(Map<String, dynamic> map) {
    List<OrderItem> parseItems(dynamic value) {
      if (value is! List) return const [];
      return value
          .map<OrderItem>((e) => OrderItem.fromMap(e as Map<String, dynamic>))
          .toList();
    }

    final customer = map['customers'] as Map<String, dynamic>?;
    return Order(
      id: map['id']?.toString(),
      customerId: map['customer_id']?.toString(),
      customerName: customer?['name']?.toString() ?? '',
      orderNumber: map['order_number']?.toString() ?? '',
      status: map['status'] ?? 'draft',
      orderDate: map['order_date'] != null
          ? DateTime.parse(map['order_date'].toString())
          : DateTime.now(),
      notes: map['notes'] ?? '',
      items: parseItems(map['order_items']),
      sellerId: map['seller_id']?.toString(),
      createdAt: map['created_at'] != null
          ? DateTime.parse(map['created_at'])
          : null,
      saleChannel: map['sale_channel']?.toString() ?? 'manual',
      commissionRate:   (map['commission_rate']   as num?)?.toDouble() ?? 0,
      commissionAmount: (map['commission_amount'] as num?)?.toDouble() ?? 0,
      sellerPayout:     (map['seller_payout']     as num?)?.toDouble() ?? 0,
      orderTotal:       (map['order_total']        as num?)?.toDouble() ?? 0,
    );
  }

  Map<String, dynamic> toMap() => {
        'customer_id':      customerId,
        'status':           status,
        'order_date':
            '${orderDate.year.toString().padLeft(4, '0')}-'
            '${orderDate.month.toString().padLeft(2, '0')}-'
            '${orderDate.day.toString().padLeft(2, '0')}',
        'notes':            notes,
        'seller_id':        sellerId,
        'sale_channel':     saleChannel,
        'commission_rate':  commissionRate,
        'commission_amount': commissionAmount,
        'seller_payout':    sellerPayout,
        'order_total':      orderTotal,
      };

  Order copyWith({
    String? id,
    Object? customerId = _omitted,
    String? customerName,
    String? orderNumber,
    String? status,
    DateTime? orderDate,
    String? notes,
    List<OrderItem>? items,
    Object? sellerId = _omitted,
    DateTime? createdAt,
    String? saleChannel,
    double? commissionRate,
    double? commissionAmount,
    double? sellerPayout,
    double? orderTotal,
  }) {
    return Order(
      id: id ?? this.id,
      customerId: identical(customerId, _omitted)
          ? this.customerId
          : customerId as String?,
      customerName: customerName ?? this.customerName,
      orderNumber: orderNumber ?? this.orderNumber,
      status: status ?? this.status,
      orderDate: orderDate ?? this.orderDate,
      notes: notes ?? this.notes,
      items: items ?? this.items,
      sellerId:
          identical(sellerId, _omitted) ? this.sellerId : sellerId as String?,
      createdAt: createdAt ?? this.createdAt,
      saleChannel:     saleChannel     ?? this.saleChannel,
      commissionRate:  commissionRate   ?? this.commissionRate,
      commissionAmount: commissionAmount ?? this.commissionAmount,
      sellerPayout:    sellerPayout     ?? this.sellerPayout,
      orderTotal:      orderTotal       ?? this.orderTotal,
    );
  }
}

const _omitted = Object();
