class PurchaseItem {
  final String? id;
  final String? purchaseId;

  final String gemType;
  final int quantity;

  /// This line's share of the purchase's total landed cost.
  /// Computed by the repository as: quantity × (totalLandedCost / totalQty).
  final double allocatedCost;

  final String notes;

  const PurchaseItem({
    this.id,
    this.purchaseId,
    required this.gemType,
    this.quantity = 1,
    required this.allocatedCost,
    this.notes = '',
  });

  double get costPerGem =>
      quantity > 0 ? allocatedCost / quantity : 0;

  factory PurchaseItem.fromMap(Map<String, dynamic> map) {
    return PurchaseItem(
      id: map['id']?.toString(),
      purchaseId: map['purchase_id']?.toString(),
      gemType: map['gem_type'] ?? '',
      quantity: (map['quantity'] ?? 1) as int,
      allocatedCost: (map['allocated_cost'] ?? 0).toDouble(),
      notes: map['notes'] ?? '',
    );
  }

  Map<String, dynamic> toMap() => {
        if (purchaseId != null) 'purchase_id': purchaseId,
        'gem_type': gemType,
        'quantity': quantity,
        'allocated_cost': allocatedCost,
        'notes': notes,
      };

  PurchaseItem copyWith({
    String? id,
    String? purchaseId,
    String? gemType,
    int? quantity,
    double? allocatedCost,
    String? notes,
  }) {
    return PurchaseItem(
      id: id ?? this.id,
      purchaseId: purchaseId ?? this.purchaseId,
      gemType: gemType ?? this.gemType,
      quantity: quantity ?? this.quantity,
      allocatedCost: allocatedCost ?? this.allocatedCost,
      notes: notes ?? this.notes,
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────

class Purchase {
  final String? id;
  final String? supplierId;

  // Join-derived from suppliers table.
  final String supplierName;

  // Auto-generated by DB sequence — not sent on insert.
  final String purchaseNumber;

  final DateTime purchaseDate;
  final double gemCost;
  final double shippingCost;
  final double customsCost;
  final double otherFees;
  final String notes;

  // Populated when loaded via getPurchaseDetail.
  final List<PurchaseItem> items;

  final String? branchId;
  final DateTime? createdAt;

  const Purchase({
    this.id,
    this.supplierId,
    this.supplierName = '',
    this.purchaseNumber = '',
    required this.purchaseDate,
    required this.gemCost,
    this.shippingCost = 0,
    this.customsCost = 0,
    this.otherFees = 0,
    required this.notes,
    this.items = const [],
    this.branchId,
    this.createdAt,
  });

  double get totalCost => gemCost + shippingCost + customsCost + otherFees;

  int get totalGems =>
      items.fold(0, (sum, i) => sum + i.quantity);

  double get costPerGem =>
      totalGems > 0 ? totalCost / totalGems : 0;

  factory Purchase.fromMap(Map<String, dynamic> map) {
    List<PurchaseItem> parseItems(dynamic value) {
      if (value is! List) return const [];
      return value
          .map<PurchaseItem>(
              (e) => PurchaseItem.fromMap(e as Map<String, dynamic>))
          .toList();
    }

    final supplier = map['suppliers'] as Map<String, dynamic>?;
    return Purchase(
      id: map['id']?.toString(),
      supplierId: map['supplier_id']?.toString(),
      supplierName: supplier?['name']?.toString() ?? '',
      purchaseNumber: map['purchase_number']?.toString() ?? '',
      purchaseDate: map['purchase_date'] != null
          ? DateTime.parse(map['purchase_date'].toString())
          : DateTime.now(),
      gemCost: (map['gem_cost'] ?? 0).toDouble(),
      shippingCost: (map['shipping_cost'] ?? 0).toDouble(),
      customsCost: (map['customs_cost'] ?? 0).toDouble(),
      otherFees: (map['other_fees'] ?? 0).toDouble(),
      notes: map['notes'] ?? '',
      items: parseItems(map['purchase_items']),
      branchId: map['branch_id']?.toString(),
      createdAt: map['created_at'] != null
          ? DateTime.parse(map['created_at'])
          : null,
    );
  }

  /// Does NOT include purchase_number (auto-generated by DB) or items.
  Map<String, dynamic> toMap() => {
        'supplier_id': supplierId,
        'purchase_date':
            '${purchaseDate.year.toString().padLeft(4, '0')}-'
            '${purchaseDate.month.toString().padLeft(2, '0')}-'
            '${purchaseDate.day.toString().padLeft(2, '0')}',
        'gem_cost': gemCost,
        'shipping_cost': shippingCost,
        'customs_cost': customsCost,
        'other_fees': otherFees,
        'total_cost': totalCost,
        'notes': notes,
        'branch_id': branchId,
      };

  Purchase copyWith({
    String? id,
    Object? supplierId = _omitted,
    String? supplierName,
    String? purchaseNumber,
    DateTime? purchaseDate,
    double? gemCost,
    double? shippingCost,
    double? customsCost,
    double? otherFees,
    String? notes,
    List<PurchaseItem>? items,
    Object? branchId = _omitted,
    DateTime? createdAt,
  }) {
    return Purchase(
      id: id ?? this.id,
      supplierId: identical(supplierId, _omitted)
          ? this.supplierId
          : supplierId as String?,
      supplierName: supplierName ?? this.supplierName,
      purchaseNumber: purchaseNumber ?? this.purchaseNumber,
      purchaseDate: purchaseDate ?? this.purchaseDate,
      gemCost: gemCost ?? this.gemCost,
      shippingCost: shippingCost ?? this.shippingCost,
      customsCost: customsCost ?? this.customsCost,
      otherFees: otherFees ?? this.otherFees,
      notes: notes ?? this.notes,
      items: items ?? this.items,
      branchId:
          identical(branchId, _omitted) ? this.branchId : branchId as String?,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}

const _omitted = Object();
